# Generated by Django 4.2.15 on 2024-08-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_update_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_on',
        ),
    ]
